### ISSUE TITLE
It might be worth it to compare it with Openstruct (besides speed)

### ISSUE THREAD

**Issue by kikito** [arturoherrero/ofstruct#1]
Here're Ruby's standard tests for Openstruct:

https://github.com/ruby/ruby/blob/trunk/test/ostruct/test_ostruct.rb

It might be useful to run those same tests on ofstruct and see if there are any differences (and if they are, document them)

**Comment by arturoherrero** [comment]
Good idea! Two main differences:
1. OpenFastStruct doesn't allow hash access like `person[:name]`
2. OpenFastStruct allows infinite chaining of attributes

Anyway, I'm going to update the documentation.
