### ISSUE TITLE
Recurse hashes in init

### ISSUE THREAD

**Issue by brauliobo** [arturoherrero/ofstruct#24]
Currently, nested hashes aren't supported for method access. This makes it hard to work for instance with JSONs from the internet.
```
[4] 3.1.2 :001 > require 'ofstruct'; h=OpenFastStruct.new a: {b: 1}
=> #<OpenFastStruct :a={:b=>1}>
[5] 3.1.2 :002 > h
=> #<OpenFastStruct :a={:b=>1}>
[6] 3.1.2 :003 > h.a.b
NoMethodError: undefined method `b' for {:b=>1}:Hash
```

**Comment by arturoherrero** [comment]
Hi @brauliobo, I've created https://github.com/arturoherrero/ofstruct/pull/26 to allow the initialization of an `OpenFastStruct` object with recursive hashes.

Your example should work, but to preserve API consistency, **intermediate objects are `OpenFastStruct` objects**.
```ruby
> h = OpenFastStruct.new(a: { b: 1 })
=> #<OpenFastStruct :a=#<OpenFastStruct :b=1>>
> > h.a.b
=> 1
> h.a
=> #<OpenFastStruct :b=1>
```

This is the same behavior as creating a _black hole_ object ([see the README section](https://github.com/arturoherrero/ofstruct#black-hole-object)):
```ruby
> person = OpenFastStruct.new
> person.address.number = 4
=> 4
> person.address
=> #<OpenFastStruct :number=4>
```

This is ready to go, what do you think?

**Comment by brauliobo** [comment]
looks great @arturoherrero ! Indeed it is import to keep nested objects as OpenFastStruct for easy handle of JSONs

**Comment by brauliobo** [comment]
one missing case though @arturoherrero. In JSONs it is very common to have array of hashes. Hashie::Mash convert them too.

Can you handle arrays too?

**Comment by arturoherrero** [comment]
@brauliobo, Can you give me an example or the spec you need? You can create a test for https://github.com/arturoherrero/ofstruct/pull/26 and then we can try to implement it 😉

**Comment by brauliobo** [comment]
please merge this as it is now, I'll open a separate issue or PR

**Comment by arturoherrero** [comment]
Done. I need to prepare a new RubyGems release.

**Comment by arturoherrero** [comment]
@brauliobo Done

- https://github.com/arturoherrero/ofstruct/releases/tag/0.3.0
- https://rubygems.org/gems/ofstruct/versions/0.3.0
